//
//  Presidents.swift
//  US-Presidents
//
//  Created by Branden Clark on 9/5/19.
//  Copyright © 2019 Branden Clark. All rights reserved.
//

import Foundation

struct Presidents {
    static let BaseUrl = "https://upload.wikimedia.org/wikipedia/commons"
    static let List = [
        President(presidency: 1, lastName: "Washington", givenNames: "George", tookOffice: "1789-04-30", leftOffice: "1797-03-04", party: "Unaffiliated", homeState: "Virginia", portraitUrl: "/b/b6/Gilbert_Stuart_Williamstown_Portrait_of_George_Washington.jpg", thumbnailUrl: "/thumb/b/b6/Gilbert_Stuart_Williamstown_Portrait_of_George_Washington.jpg/330px-Gilbert_Stuart_Williamstown_Portrait_of_George_Washington.jpg"),
        President(presidency: 2, lastName: "Adams", givenNames: "John", tookOffice: "1797-03-04", leftOffice: "1801-03-04", party: "Federalist", homeState: "Massachusetts", portraitUrl: "/7/70/John_Adams%2C_Gilbert_Stuart%2C_c1800_1815.jpg", thumbnailUrl: "/thumb/7/70/John_Adams%2C_Gilbert_Stuart%2C_c1800_1815.jpg/330px-John_Adams%2C_Gilbert_Stuart%2C_c1800_1815.jpg"),
        President(presidency: 3, lastName: "Jefferson", givenNames: "Thomas", tookOffice: "1801-03-04", leftOffice: "1809-03-04", party: "Democratic-Republican", homeState: "Virginia", portraitUrl: "/1/1e/Thomas_Jefferson_by_Rembrandt_Peale%2C_1800.jpg", thumbnailUrl: "/thumb/1/1e/Thomas_Jefferson_by_Rembrandt_Peale%2C_1800.jpg/330px-Thomas_Jefferson_by_Rembrandt_Peale%2C_1800.jpg"),
        President(presidency: 4, lastName: "Madison", givenNames: "James", tookOffice: "1809-03-04", leftOffice: "1817-03-04", party: "Democratic-Republican", homeState: "Virginia", portraitUrl: "/1/1d/James_Madison.jpg", thumbnailUrl: "/thumb/1/1d/James_Madison.jpg/330px-James_Madison.jpg"),
        President(presidency: 5, lastName: "Monroe", givenNames: "James", tookOffice: "1817-03-04", leftOffice: "1825-03-04", party: "Democratic-Republican", homeState: "Virginia", portraitUrl: "/d/d4/James_Monroe_White_House_portrait_1819.jpg", thumbnailUrl: "/thumb/d/d4/James_Monroe_White_House_portrait_1819.jpg/330px-James_Monroe_White_House_portrait_1819.jpg"),
        President(presidency: 6, lastName: "Adams", givenNames: "John Quincy", tookOffice: "1825-03-04", leftOffice: "1829-03-04", party: "Democratic-Republican/National Republican", homeState: "Massachusetts", portraitUrl: "/2/25/John_Quincy_Adams_cropped.jpg", thumbnailUrl: "/thumb/2/25/John_Quincy_Adams_cropped.jpg/330px-John_Quincy_Adams_cropped.jpg"),
        President(presidency: 7, lastName: "Jackson", givenNames: "Andrew", tookOffice: "1829-03-04", leftOffice: "1837-03-04", party: "Democratic", homeState: "Tennessee", portraitUrl: "/4/43/Andrew_jackson_head.jpg", thumbnailUrl: "/thumb/4/43/Andrew_jackson_head.jpg/330px-Andrew_jackson_head.jpg"),
        President(presidency: 8, lastName: "Van Buren", givenNames: "Martin", tookOffice: "1837-03-04", leftOffice: "1841-03-04", party: "Democratic", homeState: "New York", portraitUrl: "/9/94/Martin_Van_Buren_edit.jpg", thumbnailUrl: "/thumb/9/94/Martin_Van_Buren_edit.jpg/330px-Martin_Van_Buren_edit.jpg"),
        President(presidency: 9, lastName: "Harrison", givenNames: "William Henry", tookOffice: "1841-03-04", leftOffice: "1841-04-04", party: "Whig", homeState: "Ohio", portraitUrl: "/c/c5/William_Henry_Harrison_daguerreotype_edit.jpg", thumbnailUrl: "/thumb/c/c5/William_Henry_Harrison_daguerreotype_edit.jpg/330px-William_Henry_Harrison_daguerreotype_edit.jpg"),
        President(presidency: 10, lastName: "Tyler", givenNames: "John", tookOffice: "1841-04-04", leftOffice: "1845-03-04", party: "Whig/Unaffiliated", homeState: "Virginia", portraitUrl: "/2/2f/Tyler_Daguerreotype_crop_%28restoration%29.jpg", thumbnailUrl: "/thumb/2/2f/Tyler_Daguerreotype_crop_%28restoration%29.jpg/330px-Tyler_Daguerreotype_crop_%28restoration%29.jpg"),
        President(presidency: 11, lastName: "Polk", givenNames: "James K.", tookOffice: "1845-03-04", leftOffice: "1849-03-04", party: "Democratic", homeState: "Tennessee", portraitUrl: "/5/5e/JKP.jpg", thumbnailUrl: "/thumb/5/5e/JKP.jpg/330px-JKP.jpg"),
        President(presidency: 12, lastName: "Taylor", givenNames: "Zachary", tookOffice: "1849-03-04", leftOffice: "1850-07-09", party: "Whig", homeState: "Louisiana", portraitUrl: "/5/51/Zachary_Taylor_restored_and_cropped.jpg", thumbnailUrl: "/thumb/5/51/Zachary_Taylor_restored_and_cropped.jpg/330px-Zachary_Taylor_restored_and_cropped.jpg"),
        President(presidency: 13, lastName: "Fillmore", givenNames: "Millard", tookOffice: "1850-07-09", leftOffice: "1853-03-04", party: "Whig", homeState: "New York", portraitUrl: "/d/dd/Millard_Fillmore_by_Brady_Studio_1855-65-crop.jpg", thumbnailUrl: "/thumb/d/dd/Millard_Fillmore_by_Brady_Studio_1855-65-crop.jpg/330px-Millard_Fillmore_by_Brady_Studio_1855-65-crop.jpg"),
        President(presidency: 14, lastName: "Pierce", givenNames: "Franklin", tookOffice: "1853-03-04", leftOffice: "1857-03-04", party: "Democratic", homeState: "New Hampshire", portraitUrl: "/8/87/Franklin_Pierce_-_Cropped.jpg", thumbnailUrl: "/thumb/8/87/Franklin_Pierce_-_Cropped.jpg/330px-Franklin_Pierce_-_Cropped.jpg"),
        President(presidency: 15, lastName: "Buchanan", givenNames: "James", tookOffice: "1857-03-04", leftOffice: "1861-03-04", party: "Democratic", homeState: "Pennsylvania", portraitUrl: "/f/fd/James_Buchanan.jpg", thumbnailUrl: "/thumb/f/fd/James_Buchanan.jpg/330px-James_Buchanan.jpg"),
        President(presidency: 16, lastName: "Lincoln", givenNames: "Abraham", tookOffice: "1861-03-04", leftOffice: "1865-04-15", party: "Republican (National Union)", homeState: "Illinois", portraitUrl: "/a/ab/Abraham_Lincoln_O-77_matte_collodion_print.jpg", thumbnailUrl: "/thumb/a/ab/Abraham_Lincoln_O-77_matte_collodion_print.jpg/330px-Abraham_Lincoln_O-77_matte_collodion_print.jpg"),
        President(presidency: 17, lastName: "Johnson", givenNames: "Andrew", tookOffice: "1865-04-15", leftOffice: "1869-03-04", party: "National Union/Democratic", homeState: "Tennessee", portraitUrl: "/e/e6/Andrew_Johnson_photo_portrait_head_and_shoulders%2C_c1870-1880-Edit1.jpg", thumbnailUrl: "/thumb/e/e6/Andrew_Johnson_photo_portrait_head_and_shoulders%2C_c1870-1880-Edit1.jpg/330px-Andrew_Johnson_photo_portrait_head_and_shoulders%2C_c1870-1880-Edit1.jpg"),
        President(presidency: 18, lastName: "Grant", givenNames: "Ulysses S.", tookOffice: "1869-03-04", leftOffice: "1877-03-04", party: "Republican", homeState: "Ohio", portraitUrl: "/7/75/Ulysses_S_Grant_by_Brady_c1870-restored.jpg", thumbnailUrl: "/thumb/7/75/Ulysses_S_Grant_by_Brady_c1870-restored.jpg/330px-Ulysses_S_Grant_by_Brady_c1870-restored.jpg"),
        President(presidency: 19, lastName: "Hayes", givenNames: "Rutherford B.", tookOffice: "1877-03-04", leftOffice: "1881-03-04", party: "Republican", homeState: "Ohio", portraitUrl: "/5/50/President_Rutherford_Hayes_1870_-_1880_Restored.jpg", thumbnailUrl: "/thumb/5/50/President_Rutherford_Hayes_1870_-_1880_Restored.jpg/330px-President_Rutherford_Hayes_1870_-_1880_Restored.jpg"),
        President(presidency: 20, lastName: "Garfield", givenNames: "James A.", tookOffice: "1881-03-04", leftOffice: "1881-09-19", party: "Republican", homeState: "Ohio", portraitUrl: "/1/1f/James_Abram_Garfield%2C_photo_portrait_seated.jpg", thumbnailUrl: "/thumb/1/1f/James_Abram_Garfield%2C_photo_portrait_seated.jpg/330px-James_Abram_Garfield%2C_photo_portrait_seated.jpg"),
        President(presidency: 21, lastName: "Arthur", givenNames: "Chester A.", tookOffice: "1881-09-19", leftOffice: "1885-03-04", party: "Republican", homeState: "New York", portraitUrl: "/7/79/Chester_Alan_Arthur.jpg", thumbnailUrl: "/thumb/7/79/Chester_Alan_Arthur.jpg/330px-Chester_Alan_Arthur.jpg"),
        President(presidency: 22, lastName: "Cleveland", givenNames: "Grover", tookOffice: "1885-03-04", leftOffice: "1889-03-04", party: "Democratic", homeState: "New York", portraitUrl: "/f/f3/Grover_Cleveland_-_NARA_-_518139_%28cropped%29.jpg", thumbnailUrl: "/thumb/f/f3/Grover_Cleveland_-_NARA_-_518139_%28cropped%29.jpg/330px-Grover_Cleveland_-_NARA_-_518139_%28cropped%29.jpg"),
        President(presidency: 23, lastName: "Harrison", givenNames: "Benjamin", tookOffice: "1889-03-04", leftOffice: "1893-03-04", party: "Republican", homeState: "Indiana", portraitUrl: "/f/f8/Benjamin_Harrison%2C_head_and_shoulders_bw_photo%2C_1896.jpg", thumbnailUrl: "/thumb/f/f8/Benjamin_Harrison%2C_head_and_shoulders_bw_photo%2C_1896.jpg/330px-Benjamin_Harrison%2C_head_and_shoulders_bw_photo%2C_1896.jpg"),
        President(presidency: 24, lastName: "Cleveland", givenNames: "Grover", tookOffice: "1893-03-04", leftOffice: "1897-03-04", party: "Democratic", homeState: "New York", portraitUrl: "/f/f3/Grover_Cleveland_-_NARA_-_518139_%28cropped%29.jpg", thumbnailUrl: "/thumb/f/f3/Grover_Cleveland_-_NARA_-_518139_%28cropped%29.jpg/330px-Grover_Cleveland_-_NARA_-_518139_%28cropped%29.jpg"),
        President(presidency: 25, lastName: "McKinley", givenNames: "William", tookOffice: "1897-03-04", leftOffice: "1901-09-14", party: "Republican", homeState: "Ohio", portraitUrl: "/6/6d/Mckinley.jpg", thumbnailUrl: "/thumb/6/6d/Mckinley.jpg/330px-Mckinley.jpg"),
        President(presidency: 26, lastName: "Roosevelt", givenNames: "Theodore", tookOffice: "1901-09-14", leftOffice: "1909-03-04", party: "Republican", homeState: "New York", portraitUrl: "/1/1c/President_Roosevelt_-_Pach_Bros.jpg", thumbnailUrl: "/thumb/1/1c/President_Roosevelt_-_Pach_Bros.jpg/330px-President_Roosevelt_-_Pach_Bros.jpg"),
        President(presidency: 27, lastName: "Taft", givenNames: "William Howard", tookOffice: "1909-03-04", leftOffice: "1913-03-04", party: "Republican", homeState: "Ohio", portraitUrl: "/3/39/William_Howard_Taft%2C_head-and-shoulders_portrait%2C_facing_front.jpg", thumbnailUrl: "/thumb/3/39/William_Howard_Taft%2C_head-and-shoulders_portrait%2C_facing_front.jpg/330px-William_Howard_Taft%2C_head-and-shoulders_portrait%2C_facing_front.jpg"),
        President(presidency: 28, lastName: "Wilson", givenNames: "Woodrow", tookOffice: "1913-03-04", leftOffice: "1921-03-04", party: "Democratic", homeState: "New Jersey", portraitUrl: "/4/4d/Woodrow_Wilson-H%26E.jpg", thumbnailUrl: "/thumb/4/4d/Woodrow_Wilson-H%26E.jpg/330px-Woodrow_Wilson-H%26E.jpg"),
        President(presidency: 29, lastName: "Harding", givenNames: "Warren G.", tookOffice: "1921-03-04", leftOffice: "1923-08-02", party: "Republican", homeState: "Ohio", portraitUrl: "/c/c4/Warren_G_Harding-Harris_%26_Ewing.jpg", thumbnailUrl: "/thumb/c/c4/Warren_G_Harding-Harris_%26_Ewing.jpg/330px-Warren_G_Harding-Harris_%26_Ewing.jpg"),
        President(presidency: 30, lastName: "Coolidge", givenNames: "Calvin", tookOffice: "1923-08-02", leftOffice: "1929-03-04", party: "Republican", homeState: "Massachusetts", portraitUrl: "/3/37/Calvin_Coolidge%2C_bw_head_and_shoulders_photo_portrait_seated%2C_1919.jpg", thumbnailUrl: "/thumb/3/37/Calvin_Coolidge%2C_bw_head_and_shoulders_photo_portrait_seated%2C_1919.jpg/330px-Calvin_Coolidge%2C_bw_head_and_shoulders_photo_portrait_seated%2C_1919.jpg"),
        President(presidency: 31, lastName: "Hoover", givenNames: "Herbert", tookOffice: "1929-03-04", leftOffice: "1933-03-04", party: "Republican", homeState: "Iowa", portraitUrl: "/5/57/President_Hoover_portrait.jpg", thumbnailUrl: "/thumb/5/57/President_Hoover_portrait.jpg/330px-President_Hoover_portrait.jpg"),
        President(presidency: 32, lastName: "Roosevelt", givenNames: "Franklin D.", tookOffice: "1933-03-04", leftOffice: "1945-04-12", party: "Democratic", homeState: "New York", portraitUrl: "/4/42/FDR_1944_Color_Portrait.jpg", thumbnailUrl: "/thumb/4/42/FDR_1944_Color_Portrait.jpg/330px-FDR_1944_Color_Portrait.jpg"),
        President(presidency: 33, lastName: "Truman", givenNames: "Harry S.", tookOffice: "1945-04-12", leftOffice: "1953-01-20", party: "Democratic", homeState: "Missouri", portraitUrl: "/1/1e/Truman_58-766-09.jpg", thumbnailUrl: "/1/1e/Truman_58-766-09.jpg"),
        President(presidency: 34, lastName: "Eisenhower", givenNames: "Dwight D.", tookOffice: "1953-01-20", leftOffice: "1961-01-20", party: "Republican", homeState: "Texas", portraitUrl: "/d/d8/President_Eisenhower_Portrait_1959.jpg", thumbnailUrl: "/thumb/d/d8/President_Eisenhower_Portrait_1959.jpg/330px-President_Eisenhower_Portrait_1959.jpg"),
        President(presidency: 35, lastName: "Kennedy", givenNames: "John F.", tookOffice: "1961-01-20", leftOffice: "1963-11-22", party: "Democratic", homeState: "Massachusetts", portraitUrl: "/c/c3/John_F._Kennedy%2C_White_House_color_photo_portrait.jpg", thumbnailUrl: "/thumb/c/c3/John_F._Kennedy%2C_White_House_color_photo_portrait.jpg/330px-John_F._Kennedy%2C_White_House_color_photo_portrait.jpg"),
        President(presidency: 36, lastName: "Johnson", givenNames: "Lyndon B.", tookOffice: "1963-11-22", leftOffice: "1969-01-20", party: "Democratic", homeState: "Texas", portraitUrl: "/c/c3/37_Lyndon_Johnson_3x4.jpg", thumbnailUrl: "/thumb/c/c3/37_Lyndon_Johnson_3x4.jpg/330px-37_Lyndon_Johnson_3x4.jpg"),
        President(presidency: 37, lastName: "Nixon", givenNames: "Richard", tookOffice: "1969-01-20", leftOffice: "1974-08-09", party: "Republican", homeState: "California", portraitUrl: "/3/39/Richard_M._Nixon%2C_ca._1935_-_1982_-_NARA_-_530679.jpg", thumbnailUrl: "/thumb/3/39/Richard_M._Nixon%2C_ca._1935_-_1982_-_NARA_-_530679.jpg/330px-Richard_M._Nixon%2C_ca._1935_-_1982_-_NARA_-_530679.jpg"),
        President(presidency: 38, lastName: "Ford", givenNames: "Gerald", tookOffice: "1974-08-09", leftOffice: "1977-01-20", party: "Republican", homeState: "Michigan", portraitUrl: "/6/6b/Gerald_Ford_-_NARA_-_530680.jpg", thumbnailUrl: "/thumb/6/6b/Gerald_Ford_-_NARA_-_530680.jpg/330px-Gerald_Ford_-_NARA_-_530680.jpg"),
        President(presidency: 39, lastName: "Carter", givenNames: "Jimmy", tookOffice: "1977-01-20", leftOffice: "1981-01-20", party: "Democratic", homeState: "Georgia", portraitUrl: "/5/5a/JimmyCarterPortrait2.jpg", thumbnailUrl: "/thumb/5/5a/JimmyCarterPortrait2.jpg/330px-JimmyCarterPortrait2.jpg"),
        President(presidency: 40, lastName: "Reagan", givenNames: "Ronald", tookOffice: "1981-01-20", leftOffice: "1989-01-20", party: "Republican", homeState: "California", portraitUrl: "/1/16/Official_Portrait_of_President_Reagan_1981.jpg", thumbnailUrl: "/thumb/1/16/Official_Portrait_of_President_Reagan_1981.jpg/330px-Official_Portrait_of_President_Reagan_1981.jpg"),
        President(presidency: 41, lastName: "Bush", givenNames: "George H. W.", tookOffice: "1989-01-20", leftOffice: "1993-01-20", party: "Republican", homeState: "Texas", portraitUrl: "/f/ff/George_H._W._Bush%2C_President_of_the_United_States%2C_1989_official_portrait_cropped.jpg", thumbnailUrl: "/thumb/f/ff/George_H._W._Bush%2C_President_of_the_United_States%2C_1989_official_portrait_cropped.jpg/330px-George_H._W._Bush%2C_President_of_the_United_States%2C_1989_official_portrait_cropped.jpg"),
        President(presidency: 42, lastName: "Clinton", givenNames: "Bill", tookOffice: "1993-01-20", leftOffice: "2001-01-20", party: "Democratic", homeState: "Arkansas", portraitUrl: "/d/d3/Bill_Clinton.jpg", thumbnailUrl: "/thumb/d/d3/Bill_Clinton.jpg/330px-Bill_Clinton.jpg"),
        President(presidency: 43, lastName: "Bush", givenNames: "George W.", tookOffice: "2001-01-20", leftOffice: "2009-01-20", party: "Republican", homeState: "Texas", portraitUrl: "/d/d4/George-W-Bush.jpeg", thumbnailUrl: "/thumb/d/d4/George-W-Bush.jpeg/330px-George-W-Bush.jpeg"),
        President(presidency: 44, lastName: "Obama", givenNames: "Barack", tookOffice: "2009-01-20", leftOffice: "2017-01-20", party: "Democratic", homeState: "Illinois", portraitUrl: "/f/f9/Obama_portrait_crop.jpg", thumbnailUrl: "/thumb/f/f9/Obama_portrait_crop.jpg/330px-Obama_portrait_crop.jpg"),
        President(presidency: 45, lastName: "Trump", givenNames: "Donald", tookOffice: "2017-01-20", leftOffice: "Incumbent", party: "Republican", homeState: "New York", portraitUrl: "/5/53/Donald_Trump_official_portrait_%28cropped%29.jpg", thumbnailUrl: "/thumb/5/53/Donald_Trump_official_portrait_%28cropped%29.jpg/330px-Donald_Trump_official_portrait_%28cropped%29.jpg")
    ]

}
